import type { Metadata } from "next";
// 이 타입은 페이지의 메타데이터를 정의할 때 사용된다.
import { Inter } from "next/font/google";
// 구글 폰트들에서 inter폰트를 가져오기 위해 Inter함수 사용
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
// 폰트 적용할 때 사용

export const metadata: Metadata = {
  //이 메타데이터는 SEO(검색 엔진 최적화)와 페이지 정보 제공에 사용
  title: "Create Next App",
  description: "Generated by create next app",
};

//함수형 컴포넌트 정의
export default function RootLayout({
  children,
}: Readonly<{
  //children 매개변수 객체의 타입을 읽기 전용으로 명시
  children: React.ReactNode;
  //children 속성이 React 노드 타입
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
